
export const NOT_FOUND = 'NOT_FOUND';

export const LD_STAT = 'LD_STAT';
export const LD_STAT_REQUEST = 'LD_STAT_REQUEST';
export const LD_STAT_SUCCESS = 'LD_STAT_SUCCESS';
export const LD_STAT_FAILURE = 'LD_STAT_FAILURE';

export const SAVE_REDIRECT_STATE = 'SAVE_REDIRECT_STATE';
export const REDIRECTED_STATE_AUTHENTICATED = 'REDIRECTED_STATE_AUTHENTICATED';

export const CODE_LOADING = 'CODE_LOADING';
export const CODE_LOADED = 'CODE_LOADED';
export const CODE_LOAD_ERROR = 'CODE_LOAD_ERROR';

//set initial state of the site to loaded
export const APP_LOADED = 'APP_LOADED';
export const ROUTE_LOADED = 'ROUTE_LOADED';

export const VIEW_HOME_FEATURE_INTRO = 'VIEW_HOME_FEATURE_INTRO';

export const SEARCH = 'SEARCH';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const SHARE_EMAIL = 'SHARE_EMAIL';
export const SHARE_EMAIL_REQUEST = 'SHARE_EMAIL_REQUEST';
export const SHARE_EMAIL_SUCCESS = 'SHARE_EMAIL_SUCCESS';
export const SHARE_EMAIL_FAILURE = 'SHARE_EMAIL_FAILURE';

export const NEWS_FEED = 'NEWS_FEED';
export const NEWS_FEED_REQUEST = 'NEWS_FEED_REQUEST';
export const NEWS_FEED_SUCCESS = 'NEWS_FEED_SUCCESS';
export const NEWS_FEED_FAILURE = 'NEWS_FEED_FAILURE';

export const FULL_SCREEN = 'FULL_SCREEN';

export const EMBED_MODE = 'EMBED_MODE';

export const SITE_MODE = 'SITE_MODE';
export const SITE_MODE_APP = 'app';
export const SITE_MODE_ADMIN = 'admin';
export const SITE_MODE_PAGE = 'page';

export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const POST_FEEDBACK = 'POST_FEEDBACK';
export const POST_FEEDBACK_REQUEST = 'POST_FEEDBACK_REQUEST';
export const POST_FEEDBACK_SUCCESS = 'POST_FEEDBACK_SUCCESS';
export const POST_FEEDBACK_FAILURE = 'POST_FEEDBACK_FAILURE';

export const CLOSE_NET_ERROR_MESSAGE = 'CLOSE_NET_ERROR_MESSAGE';
export const CLOSE_ANNOUNCE_MESSAGE = 'CLOSE_ANNOUNCE_MESSAGE';

export const PENDING_ACTION = 'PENDING_ACTION';
export const RESET_PENDING = 'RESET_PENDING';

export const NOOP = 'noop';

export const APP_ERROR = 'APP_ERROR';
export const APP_MESSAGE = 'APP_MESSAGE';
/*
export const PENDING_ACTION_REQUEST = 'PENDING_ACTION_REQ';
export const PENDING_ACTION_FAILURE = 'PENDING_ACTION_FAIL';
export const PENDING_ACTION_SUCCESS = 'PENDING_ACTION_SUC';
*/
